import { NextPage } from 'next';
import React from 'react';
import NavigationBar from '../components/navigation';
import ExperienceForm from '../components/experience/addExperienceForm';
import Head from 'next/head';

const Experience: NextPage = (): JSX.Element => {
    return (
        <>
            <Head>
                <title>Admin Dashboard</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <NavigationBar pages={['Projects', 'Experience']} />
            <ExperienceForm />
        </>
    )
}

export default Experience;