import type { NextPage } from 'next'
import Head from 'next/head'
import NavigationBar from '../components/navigation'

const pages = ['Projects', 'Experiences'];

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Admin Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavigationBar pages={pages} />
    </div>
  )
}

export default Home
