import React from 'react';
import NavigationBar from '../components/navigation';
import ProjectForm from '../components/projects/addProjectForm';
import Head from 'next/head'
import { NextPage } from 'next';
import { Typography } from '@mui/material';

const Projects: NextPage = (): JSX.Element => {
    return (
        <>
            <Head>
                <title>Admin Dashboard</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <NavigationBar pages={['Projects', 'Experience']} />
            <ProjectForm />
        </>
    )
}

export default Projects;